import type { NextPage } from "next";
import Head from "next/head";
import PartnersSection from "../Sections/HomeSections/PartnersSection";
import VentComplaintsSection from "../Sections/HomeSections/VentComplaintsSection";
import HeroSection from "../Sections/HomeSections/HeroSection";
import styles from "../styles/Home.module.css";
import { Footer, GoalCard, NavBar } from "../components";
import PostaComplaint from "../Sections/HomeSections/PostaComplaint";
import Testimonials from "../Sections/HomeSections/TestimonialsSection";
import Numbers from "../Sections/HomeSections/Numbers";
import OurGoalsSection from "../Sections/HomeSections/OurGoalsSection";
import HowDoesItWork from "../Sections/HomeSections/HowDoesItWork";
import AOS from "aos";
import { useEffect, useState } from "react";
import Menu from "components/MenuComp";
import { motion } from "framer-motion";
import Slider from "components/Slider";
import Image from "next/image";

const Home: NextPage = () => {
	useEffect(() => {
		AOS.init();
	}, []);
	const [expand, setExpand] = useState(false);
	const [currentSlide, setCurrentSlide] = useState(0);
	// const setNextSlide = () => {
	// 	let index = currentSlide;
	// 	if (index == 2) {
	// 		setCurrentSlide(0);
	// 	} else setCurrentSlide(index + 1);

	// 	console.log(index);
	// };
	// setInterval(() => {
	// 	setNextSlide();
	// }, 3000);
	return (
		<div>
			{expand && (
				<Menu
					expand={expand}
					setExpand={setExpand}
				/>
			)}
			{!expand && (
				<div>
					<Head>
						<title>Ecommerce Complaint</title>
						<meta
							name="description"
							content="Generated by create next app"
						/>
						<link
							rel="icon"
							href="/favicon.ico"
						/>
						<link
							href="https://unpkg.com/aos@2.3.1/dist/aos.css"
							rel="stylesheet"
						></link>
					</Head>
					<NavBar
						expand={expand}
						setExpand={setExpand}
						searchIconIsPresent={true}
					/>
					<div className=" pt-[93px] mx-auto items-center justify-center text-center bg-clearblue">
						<p className="mx-auto px-2 text-[40px] sm:text-[60px] font-bold -tracking-[0.02em]">
							Make & <span className="text-eccblue">resolve</span>
							<br />
							complaints easily
						</p>

						<div className="lg:w-[380px] lg:mx-auto  ">
							<Slider />
						</div>
						<div className="relative w-full lg:w-[713px] h-[223px] sm:h-[380px] lg:h-[423px] mx-auto">
							<Image
								src="/Images/man-freaked-out.png"
								alt="man freaked out"
								layout="fill"
								objectFit="contain"
							/>
						</div>
					</div>
					<OurGoalsSection />
					<VentComplaintsSection />
					<HowDoesItWork />
					<Numbers />
					<Testimonials />
					<PartnersSection />
					<PostaComplaint />
					<Footer />
				</div>
			)}
		</div>
	);
};

export default Home;
